name: Site Lint / Heading ID check

on:
  push:
    branches:
      - main # change this if your default branch is named differently
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint on node 20.x and ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.7.10

      - name: Lint codebase
        run: yarn ci-check
